
country_names = ['afghanistan', 'albania', 'algeria', 'american samoa', 'andorra', 'angola', 
       'anguilla', 'antarctica', 'antigua and barbuda', 'argentina', 'armenia', 
       'aruba', 'australia', 'austria', 'azerbaijan', 
       'bahamas', 'bahrain', 'bangladesh', 'barbados', 'belarus', 'belgium', 'belize', 'benin', 'bermuda', 'bhutan', 'bolivia', 'bosnia and herzegovina', 'botswana', 'brazil', 'bharat', 'bhaarat',
       'brunei', 'bulgaria', 'burkina faso', 'burundi', 
       'cambodia', 'cameroon', 'canada', 'cape verde', 'cayman islands', 'central african republic', 'chad', 'chile', 'china', 'christmas island', 'cocos (keeling) islands', 'colombia', 'comoros', 'congo', 'costa rica', 'croatia', 'cuba', 'cyprus', 'czech republic', 
       'denmark', 'djibouti', 'dominica', 'dominican republic', 'deutschland', 
       'ecuador', 'egypt', 'el salvador', 'equatorial guinea', 'eritrea', 'estonia', 'eswatini','ethiopia', 
       'falkland islands', 'faroe islands', 'fiji', 'finland', 'france', 'french guiana', 
       'french polynesia', 'french southern territories', 
       'gabon', 'gambia', 'georgia', 'germany', 'ghana', 'gibraltar', 'greece', 'greenland', 'grenada', 'guadeloupe', 'guam', 'guatemala', 'guernsey', 'guinea', 'guinea-bissau', 'guyana', 
       'haiti', 'honduras', 'hong kong', 'hungary', 'hindustan',
       'iceland', 'india', 'indonesia', 'iran', 'iraq', 'ireland', 'isle of man', 'israel', 'italy', 'jamaica', 'japan', 'jersey', 'jordan', 
       'kazakhstan', 'kenya', 'kiribati', 'kuwait', 'kyrgyzstan', 
       'laos', 'latvia', 'lebanon', 'lesotho', 'liberia', 'libya', 
       'liechtenstein', 'lithuania','luxembourg', 
       'macau', 'madagascar', 'malawi', 'malaysia', 'maldives', 'mali', 'malta', 'marshall islands', 'martinique', 'mauritania', 'mauritius', 'mayotte', 'mexico', 'micronesia', 'moldova', 'monaco', 'mongolia', 'montenegro', 'montserrat', 'morocco', 'mozambique', 'myanmar', 
       'namibia', 'nauru', 'nepal', 'netherlands', 'new caledonia', 'new zealand', 'nicaragua', 'niger', 'nigeria', 'north korea', 'north macedonia', 'northern mariana islands', 'norway', 
       'oman', 
       'pakistan', 'palau', 'palestine', 'panama', 'papua new guinea', 'paraguay', 'peru', 'philippines', 'pitcairn islands', 'poland', 'portugal', 'puerto rico', 
       'qatar', 
       'romania', 'russia', 'rwanda', 
       'saint barthelemy', 'saint helena', 'saint kitts and nevis', 'saint lucia', 'saint martin', 
       'saint pierre and miquelon', 'saint vincent and the grenadines', 'samoa', 'san marino', 
       'sao tome and principe', 'saudi arabia', 'senegal', 'serbia', 'seychelles', 'sierra leone', 'singapore', 'slovakia', 'slovenia', 'solomon islands', 'somalia', 'south africa', 'south korea', 'south sudan', 'spain', 'sri lanka', 'sudan', 'suriname', 'sweden', 'switzerland', 'syria', 'taiwan', 'tajikistan', 'tanzania', 'thailand', 'timor-leste', 'togo', 'tonga', 
       'trinidad and tobago', 'tunisia', 'turkey', 'turkmenistan', 'turks and caicos islands', 'tuvalu', 
       'uganda', 'ukraine', 'united arab emirates', 'united kingdom', 'usa', 'uk',
       'united states', 'uruguay', 'uzbekistan', 
       'vanuatu', 'vatican city', 'venezuela', 'vietnam', 
       'wallis and futuna', 'western sahara', 
       'yemen', 
       'zambia', 'zimbabwe']


